version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    container_name: ntacloud-redis
    networks:
      - ntacloud-infra
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host

networks:
  ntacloud-infra:
    attachable: true
    name: ntacloud-infra
